version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: DockerfileAPI
    ports:
      - "5000:5000"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_EDGE_PORT=4566
    networks:
      - localstack-network

  tests:
    build:
      context: .
      dockerfile: DockerfileTest
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_EDGE_PORT=4566
      - API_URL=http://api:5000
    depends_on:
      - api
    networks:
      - localstack-network
    entrypoint: /bin/bash -c "while ! curl -s http://api:5000/; do sleep 5; done; pytest tests"

networks:
  localstack-network:
    driver: bridge
