version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda,dynamodb
      - DEFAULT_REGION=us-east-1
    networks:
      - localstack-network

  api:
    build:
      context: .
      dockerfile: DockerfileAPI
    ports:
      - "5000:5000"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_EDGE_PORT=4566
    networks:
      - localstack-network
    depends_on:
      - localstack
    entrypoint: /bin/bash -c "./run_localstack.sh"

  tests:
    build:
      context: .
      dockerfile: DockerfileTest
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_EDGE_PORT=4566
      - API_URL=http://api:5000
    networks:
      - localstack-network
    depends_on:
      - api
    entrypoint: /bin/bash -c "while ! curl -s http://api:5000/; do sleep 5; done; pytest ./tests/test_rest.py"

networks:
  localstack-network:
    driver: bridge
