version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
    networks:
      - localstack-network

  api:
    build:
      context: .
      dockerfile: DockerfileAPI
    ports:
      - "5000:5000"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_EDGE_PORT=4566
    depends_on:
      - localstack
    networks:
      - localstack-network

  tests:
    build:
      context: .
      dockerfile: DockerfileTest
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_EDGE_PORT=4566
    depends_on:
      - api
    networks:
      - localstack-network
    command: ["pytest", "test_rest.py"]

networks:
  localstack-network:
    driver: bridge
