version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "5000:5000"
    environment:
      - SERVICES=dynamodb,s3
    networks:
      - localstack-network
    volumes:
      - .:/app
    command: ["./run_localstack.sh"]

  tests:
    build:
      context: .
      dockerfile: DockerfileTest
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_EDGE_PORT=4566
      - API_URL=http://localstack:5000
    depends_on:
      - localstack
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge
