name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build REST API image
      run: docker build -t rest-api -f DockerfileAPI .

    - name: Run REST API container
      run: docker run -d -p 5000:5000 --name rest-api-container rest-api

    - name: Wait for API to be ready
      run: |
        echo "Waiting for API to be ready..."
        sleep 10 # Wait for 10 seconds to ensure the API is up and running

    - name: Build and run tests
      run: |
        docker build -t rest-api-test -f DockerfileTest .
        docker run --network host rest-api-test

    - name: Cleanup
      run: docker rm -f rest-api-container