name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        options: --entrypoint=/bin/sh localstack/localstack -c 'while true; do sleep 1; done'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build REST API image
      run: docker build -t rest-api -f DockerfileAPI .

    - name: Create Docker network
      run: docker network create rest-api-network

    - name: Run REST API container
      run: docker run -d --network rest-api-network --name rest-api-container -p 5000:5000 rest-api

    - name: Wait for API to be ready
      run: |
        echo "Waiting for API to be ready..."
        sleep 10 # Wait for 10 seconds to ensure the API is up and running

    - name: Build and run tests
      run: |
        docker build -t rest-api-test -f DockerfileTest .
        docker run --network rest-api-network rest-api-test

    - name: Cleanup
      run: |
        docker rm -f rest-api-container
        docker network rm rest-api-network
